/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmbassadorsRouteImport } from './routes/ambassadors'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as ChurchesRouteImport } from './routes/churches'
import { Route as GiveRouteImport } from './routes/give'
import { Route as MeetemmyRouteImport } from './routes/meetemmy'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as StartRouteImport } from './routes/start'
import { Route as StoryRouteImport } from './routes/story'
import { Route as TheGenesisMomentRouteImport } from './routes/the-genesis-moment'
import { Route as TradesIndexRouteImport } from './routes/trades.index'
import { Route as TradesTradeRouteImport } from './routes/trades.$trade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorsRoute = AmbassadorsRouteImport.update({
  id: '/ambassadors',
  path: '/ambassadors',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurchesRoute = ChurchesRouteImport.update({
  id: '/churches',
  path: '/churches',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetemmyRoute = MeetemmyRouteImport.update({
  id: '/meetemmy',
  path: '/meetemmy',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const TheGenesisMomentRoute = TheGenesisMomentRouteImport.update({
  id: '/the-genesis-moment',
  path: '/the-genesis-moment',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesIndexRoute = TradesIndexRouteImport.update({
  id: '/trades/',
  path: '/trades/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesTradeRoute = TradesTradeRouteImport.update({
  id: '/trades/$trade',
  path: '/trades/$trade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/business': typeof BusinessRoute
  '/churches': typeof ChurchesRoute
  '/give': typeof GiveRoute
  '/meetemmy': typeof MeetemmyRoute
  '/memories': typeof MemoriesRoute
  '/start': typeof StartRoute
  '/story': typeof StoryRoute
  '/the-genesis-moment': typeof TheGenesisMomentRoute
  '/trades/$trade': typeof TradesTradeRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/business': typeof BusinessRoute
  '/churches': typeof ChurchesRoute
  '/give': typeof GiveRoute
  '/meetemmy': typeof MeetemmyRoute
  '/memories': typeof MemoriesRoute
  '/start': typeof StartRoute
  '/story': typeof StoryRoute
  '/the-genesis-moment': typeof TheGenesisMomentRoute
  '/trades/$trade': typeof TradesTradeRoute
  '/trades': typeof TradesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/business': typeof BusinessRoute
  '/churches': typeof ChurchesRoute
  '/give': typeof GiveRoute
  '/meetemmy': typeof MeetemmyRoute
  '/memories': typeof MemoriesRoute
  '/start': typeof StartRoute
  '/story': typeof StoryRoute
  '/the-genesis-moment': typeof TheGenesisMomentRoute
  '/trades/$trade': typeof TradesTradeRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambassadors'
    | '/business'
    | '/churches'
    | '/give'
    | '/meetemmy'
    | '/memories'
    | '/start'
    | '/story'
    | '/the-genesis-moment'
    | '/trades/$trade'
    | '/trades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambassadors'
    | '/business'
    | '/churches'
    | '/give'
    | '/meetemmy'
    | '/memories'
    | '/start'
    | '/story'
    | '/the-genesis-moment'
    | '/trades/$trade'
    | '/trades'
  id:
    | '__root__'
    | '/'
    | '/ambassadors'
    | '/business'
    | '/churches'
    | '/give'
    | '/meetemmy'
    | '/memories'
    | '/start'
    | '/story'
    | '/the-genesis-moment'
    | '/trades/$trade'
    | '/trades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbassadorsRoute: typeof AmbassadorsRoute
  BusinessRoute: typeof BusinessRoute
  ChurchesRoute: typeof ChurchesRoute
  GiveRoute: typeof GiveRoute
  MeetemmyRoute: typeof MeetemmyRoute
  MemoriesRoute: typeof MemoriesRoute
  StartRoute: typeof StartRoute
  StoryRoute: typeof StoryRoute
  TheGenesisMomentRoute: typeof TheGenesisMomentRoute
  TradesTradeRoute: typeof TradesTradeRoute
  TradesIndexRoute: typeof TradesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassadors': {
      id: '/ambassadors'
      path: '/ambassadors'
      fullPath: '/ambassadors'
      preLoaderRoute: typeof AmbassadorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/churches': {
      id: '/churches'
      path: '/churches'
      fullPath: '/churches'
      preLoaderRoute: typeof ChurchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetemmy': {
      id: '/meetemmy'
      path: '/meetemmy'
      fullPath: '/meetemmy'
      preLoaderRoute: typeof MeetemmyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-genesis-moment': {
      id: '/the-genesis-moment'
      path: '/the-genesis-moment'
      fullPath: '/the-genesis-moment'
      preLoaderRoute: typeof TheGenesisMomentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/': {
      id: '/trades/'
      path: '/trades'
      fullPath: '/trades/'
      preLoaderRoute: typeof TradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/$trade': {
      id: '/trades/$trade'
      path: '/trades/$trade'
      fullPath: '/trades/$trade'
      preLoaderRoute: typeof TradesTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbassadorsRoute: AmbassadorsRoute,
  BusinessRoute: BusinessRoute,
  ChurchesRoute: ChurchesRoute,
  GiveRoute: GiveRoute,
  MeetemmyRoute: MeetemmyRoute,
  MemoriesRoute: MemoriesRoute,
  StartRoute: StartRoute,
  StoryRoute: StoryRoute,
  TheGenesisMomentRoute: TheGenesisMomentRoute,
  TradesTradeRoute: TradesTradeRoute,
  TradesIndexRoute: TradesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
