/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmbassadorsRouteImport } from './routes/ambassadors'
import { Route as GiveRouteImport } from './routes/give'
import { Route as StartRouteImport } from './routes/start'
import { Route as TradesIndexRouteImport } from './routes/trades.index'
import { Route as TradesTradeRouteImport } from './routes/trades.$trade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorsRoute = AmbassadorsRouteImport.update({
  id: '/ambassadors',
  path: '/ambassadors',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesIndexRoute = TradesIndexRouteImport.update({
  id: '/trades/',
  path: '/trades/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesTradeRoute = TradesTradeRouteImport.update({
  id: '/trades/$trade',
  path: '/trades/$trade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/give': typeof GiveRoute
  '/start': typeof StartRoute
  '/trades/$trade': typeof TradesTradeRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/give': typeof GiveRoute
  '/start': typeof StartRoute
  '/trades/$trade': typeof TradesTradeRoute
  '/trades': typeof TradesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/give': typeof GiveRoute
  '/start': typeof StartRoute
  '/trades/$trade': typeof TradesTradeRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ambassadors' | '/give' | '/start' | '/trades/$trade' | '/trades/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ambassadors' | '/give' | '/start' | '/trades/$trade' | '/trades'
  id:
    | '__root__'
    | '/'
    | '/ambassadors'
    | '/give'
    | '/start'
    | '/trades/$trade'
    | '/trades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbassadorsRoute: typeof AmbassadorsRoute
  GiveRoute: typeof GiveRoute
  StartRoute: typeof StartRoute
  TradesTradeRoute: typeof TradesTradeRoute
  TradesIndexRoute: typeof TradesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassadors': {
      id: '/ambassadors'
      path: '/ambassadors'
      fullPath: '/ambassadors'
      preLoaderRoute: typeof AmbassadorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/': {
      id: '/trades/'
      path: '/trades'
      fullPath: '/trades/'
      preLoaderRoute: typeof TradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/$trade': {
      id: '/trades/$trade'
      path: '/trades/$trade'
      fullPath: '/trades/$trade'
      preLoaderRoute: typeof TradesTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbassadorsRoute: AmbassadorsRoute,
  GiveRoute: GiveRoute,
  StartRoute: StartRoute,
  TradesTradeRoute: TradesTradeRoute,
  TradesIndexRoute: TradesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
